services:

  # PostgreSQL + PostGIS
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres_assignment
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # PySpark + JupyterLab
  pyspark-jupyter:
    build: ./spark
    user: root
    container_name: pyspark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: "yes"
    volumes:
      - streaming_data:/data:rw
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  streaming_data: